### ISSUE TITLE
bad links in HTML output

### ISSUE THREAD

**Issue by pfps** [linkeddata/dokieli#8]
In http://linked-research.270a.info/ the link for Figure 2, [2] is
http://linked-research.270a.info/#figure_lsd-sense-worldbank-2012-topic-4
but that does not appear to be a valid link in the document.

**Comment by csarven** [comment]
Thanks for the report.

**Comment by pfps** [comment]
How did the bad link get in?   A fix for the issue would be to not generate such links, not to have to edit the links by hand.

**Comment by csarven** [comment]
Your suggestion is indeed desirable and I'd like to see myself. The development thus far was focused on the quality of the PDF/print output.

We should also be careful as to not necessarily replicate the same LaTeX UX, but to create an experience for the author that makes sense in the HTML environment. Your suggestion is still very much valid but it needs to be carefully designed and executed. I will create a new issue on this.
